#!/bin/bash -e
#
# Rendezvous QTApp Windows cross-compile script
#
# Copyright (C)2013 Internet Systems Consortium, Inc.
# written by Jeroen Massar <jeroen@isc.org>
#
# Make sure that CFLAGS/LDFLAGS etc is not set...

CXLog() {
	echo "======================================"
	echo "======================================"
	echo "=== $@"
	echo "======================================"
	echo "======================================"
}

CXLog "Setting up cross-compile environment"

CXHOME=$(pwd)
MPFX=i586-mingw32msvc
AR=${MPFX}-ar
CC=${MPFX}-gcc
RANLIB=${MPFX}-ranlib
OBJDUMP=${MPFX}-objdump

PREFIX=~/.cross/mingw
SRC=${PREFIX}/src/
CROSSCFG="--build=amd64-pc-linux-gnu --host=${MPFX}"
LINKCFG="--enable-static --disable-shared"
PKGCONFIG="${PREFIX}/bin/${MPFX}-pkg-config"
DEBSRC="${PREFIX}/deb-src"
PBC="../../../pbc/"
TOOLS="bison flex m4"

CXLog "Our MingW Prefix = ${PREFIX}"

if [ "$(which ${CC})X" = "X" ];
then
	echo >&2 "Error: Please install mingw: apt-get install mingw32"
	exit 1
fi

mkdir -p ${PREFIX} 2>/dev/null

if [ ! -d ${PREFIX} ];
then
	echo >&2 "No ${PREFIX}, got sufficient permissions?"
	echo >&2 "Please create ${PREFIX} as root and chown it to a normal user"
	exit 1
fi

if [ ! -d ${PBC} ];
then
	echo >&2 "Please checkout the PBC module from git, we needs it, my precious"
	exit 1
fi

for TOOL in ${TOOLS};
do
	if [ -z $(which ${TOOL}) ];
	then
		echo >&2 "${TOOL} is missing (apt-get install ${TOOL})"
		exit 1
	fi
done

CXLog "Preparing environment"

mkdir -p ${PREFIX}/bin ${PREFIX}/lib/pkgconfig

cat >${PKGCONFIG} <<HERE
#!/bin/sh

PREFIX=${PREFIX}
export PKG_CONFIG_LIBDIR=\${PREFIX}/lib/pkgconfig

exec pkg-config "\$@"
HERE
chmod +x ${PKGCONFIG}

##############################################################################

cxenv() {
	CC="${CC} -I${PREFIX}/include -L${PREFIX}/lib" AR=${AR} RANLIB=${RANLIB} PKG_CONFIG=${PKGCONFIG} $@
}

##############################################################################

cxbuild() {
	NAME=$1
	shift
	OPTS=$@

	CONF="configure ${CROSSCFG} ${LINKCFG}"

	# zlib's configure does not understand --build and --host
	if [ "${SOURCE}" = "zlib" ];
	then
		CONF="configure"
	fi

	# OpenSSL has it's own Configure
	if [ "${SOURCE}" = "openssl" ];
	then
		# Undo Debian patches and touch Makefile otherwise it is too old
		quilt pop -a
		touch Makefile
		CONF="Configure"
	fi

	CXLog "Configuring and making ${NAME}..."

	cxenv ./${CONF} --prefix=${PREFIX} ${OPTS} && cxenv make && cxenv make install

	CXLog "done (${NAME})"
}

##############################################################################

cxlib() {
	CXLIB=$1
	SOURCE=$2
	OPTS=$3

	if [ -f ${PREFIX}/lib/${CXLIB}.a ];
	then
		CXLog "Avoiding rebuild of ${CXLIB}, already exists"
	else
		CXLog "Retrieving ${CXLIB} (${SOURCE})"

		mkdir -p ${DEBSRC}/${CXLIB}
		cd ${DEBSRC}/${CXLIB}
			rm -rf ${SOURCE}-*
		apt-get source ${SOURCE}
		cd ${SOURCE}-*

		cxbuild ${CXLIB} ${OPTS}
	fi
}

##############################################################################

cxlib libcrypto openssl "--openssldir=${PREFIX} no-shared no-idea no-mdc2 no-rc5 zlib enable-tlsext no-ssl2 mingw"
cxlib libcurl curl "${CROSSCFG} ${LINKCFG} --disable-ldap"
cxlib libgmp gmp "${CROSSCFG} ${LINKCFG}"

##############################################################################
cxpbc() {

cd ${CXHOME}
cd ${PBC}

libtoolize --force --copy
aclocal
autoheader

# Do we have a Makefile?
if [ ! -f Makefile ];
then
	automake --add-missing --copy --gnu
	autoconf
	cp -f /usr/share/misc/config.sub config.sub
	cp -f /usr/share/misc/config.guess config.guess
else
        # Not clean, thus clean it
        make clean
fi

cxbuild pbc
}

# build pbc library
cxpbc

##############################################################################

set -x

cd ${CXHOME}

# Clean it
make clean OS_NAME=Windows

cxenv make OS_NAME=Windows
cxenv make OS_NAME=Windows install

exit 0

